# Generated by Django 4.0.1 on 2022-01-27 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_calendar', '0004_remove_event_end_time_remove_event_start_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name1', models.CharField(max_length=50)),
                ('last_name2', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=9)),
                ('phone', models.IntegerField()),
                ('therapist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
