# Generated by Django 4.0.1 on 2022-01-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0006_rename_patients_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dni',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('name', 'last_name1', 'last_name2')},
        ),
    ]
