# Generated by Django 4.0.1 on 2022-01-27 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0007_alter_patient_dni_alter_patient_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_calendar.patient'),
        ),
    ]
