# Generated by Django 4.0.1 on 2022-02-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0008_event_patient'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='patient',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name1',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name2',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone',
        ),
    ]
