# Generated by Django 4.0.1 on 2022-02-08 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0010_rename_patient_patientcalendar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('season_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('weather_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('patient_calendar', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_calendar.patientcalendar')),
            ],
        ),
    ]
