# Generated by Django 4.0.1 on 2022-02-08 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0012_patientmonth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmonth',
            name='date',
        ),
    ]
