# Generated by Django 4.0.1 on 2022-02-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0014_patientmonth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='PatientMonth',
        ),
    ]
