# Generated by Django 4.0.1 on 2022-03-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0015_event_type_delete_patientmonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='template_style',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
