# Generated by Django 4.0.1 on 2022-03-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0016_event_template_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='template_style',
        ),
        migrations.AddField(
            model_name='patientcalendar',
            name='template_style',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
