# Generated by Django 4.0.1 on 2022-03-11 09:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_calendar', '0017_remove_event_template_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcalendar',
            name='name',
            field=models.CharField(default='Nombre Calendario', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='patientcalendar',
            unique_together={('name', 'therapist')},
        ),
    ]
