# Generated by Django 4.0.1 on 2022-03-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0018_alter_patientcalendar_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='url_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
