# Generated by Django 4.0.1 on 2022-05-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0020_alter_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcalendar',
            name='font_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
