# Generated by Django 4.0.1 on 2022-05-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0021_patientcalendar_font_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcalendar',
            name='font_size',
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='patientcalendar',
            name='font_style',
            field=models.CharField(default='Arial,sans-serif', max_length=15),
        ),
        migrations.AddField(
            model_name='patientcalendar',
            name='link_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
