# Generated by Django 4.0.1 on 2022-05-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0022_patientcalendar_font_size_patientcalendar_font_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcalendar',
            name='font_style',
            field=models.CharField(choices=[('Arial,sans-serif', 'Sin serifa'), ('Times,serif', 'Con serifa')], default='Arial,sans-serif', max_length=20),
        ),
    ]
