# Generated by Django 4.0.1 on 2022-05-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0024_alter_patientcalendar_font_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcalendar',
            name='text_position_event',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
