# Generated by Django 4.0.1 on 2022-05-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0025_patientcalendar_text_position_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcalendar',
            name='number_box',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
