# Generated by Django 4.0.1 on 2022-05-18 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0026_patientcalendar_number_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientcalendar',
            name='number_box',
        ),
    ]
