# Generated by Django 4.0.1 on 2022-05-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0027_remove_patientcalendar_number_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcalendar',
            name='number_box',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
