# Generated by Django 4.0.1 on 2022-05-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0028_patientcalendar_number_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientcalendar',
            name='number_box',
        ),
        migrations.AddField(
            model_name='patientcalendar',
            name='extra_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientcalendar',
            name='month_box',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patientcalendar',
            name='season_box',
            field=models.BooleanField(default=True),
        ),
    ]
