# Generated by Django 4.0.1 on 2022-05-19 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0030_patientcalendar_no_boxes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientcalendar',
            name='no_boxes',
        ),
    ]
