# Generated by Django 4.0.1 on 2022-05-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0031_remove_patientcalendar_no_boxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='header',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
