# Generated by Django 4.0.1 on 2022-05-20 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0032_event_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='header',
        ),
    ]
