# Generated by Django 4.0.1 on 2022-05-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0033_remove_event_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcalendar',
            name='header_extra_box',
            field=models.CharField(default='', max_length=20),
        ),
    ]
