# Generated by Django 4.0.1 on 2022-05-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0039_patientcalendar_header_extra_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcalendar',
            name='header_extra_box',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
